### ISSUE TITLE
[Session Replay iOS Middleware] - can not play replay session on the amplitude DashBoard.

### ISSUE THREAD

**Issue by TomFluentjoy** [amplitude/AmplitudeSessionReplay-iOS#8]
## Expected Behavior

We were expecting that we could play the session replay in the amplitude
Our organization is using the Plus plan.

## Current Behavior

We can not see any replay on the amplitude with an error like that. 

Session Unavailable
Try refreshing this page in a few minutes. This session may be unavailable due to:

Viewing this session before it is processed (~1 min)
Instrumentation issues such as incorrect device ID, API key, or project (check what’s instrumented vs. the message above)
Limited user activity where events are not processed (e.g. page bounces)
Retention time frame for sessions has passed
Session replay isn’t instrumented on all pages that the user may be viewing

To debug instrumentation issues, view the ingestion dashboard.

## Steps to Reproduce
 

1. We are using maintenance iOS SDK and here is the setup in cocoa pods:

  ```
pod 'Amplitude', :git => 'https://github.com/Amplitude/Amplitude-iOS.git'
  pod 'AmplitudeSessionReplay', :git => 'https://github.com/amplitude/AmplitudeSessionReplay-iOS.git'
  pod 'AmplitudeiOSSessionReplayMiddleware', :git => 'https://github.com/amplitude/AmplitudeSessionReplay-iOS.git'
```

3. The app is setting up like this:
```
        Amplitude.instance().defaultTracking.sessions = true
        Amplitude.instance().setDeviceId(DeviceIDManager.shared.getAppDeviceID())
        Amplitude.instance().optOut = true
        Amplitude.instance().addEventMiddleware(AmplitudeiOSSessionReplayMiddleware(sampleRate: 0.01))
        Amplitude.instance().initializeApiKey(AppEnvironment.amplitudeAPIKey)
        Amplitude.instance().logEvent("app_finished_setting_amplitude_sdk")
```

## Environment
- SDK Version: Amplitude -> 8.21.0 
-  iOS: 16.0.2

**Comment by crleona** [comment]
Hi @TomFluentjoy -
A couple of things to check in your configuration:
- `AmplitudeiOSSessionReplayMiddleware` will inherit the `optOut` setting from the `Amplitude` instance, so we would not expect replays to be captured in this scenario. However, this would also prevent the plugin from attaching the session replay id to the event, so this is a bit unexpected.
- `sampleRate` is configured to 1%, which is quite low for testing - I would raise it to 1.0 to guarantee that a session is recorded. We would still attach the session replay id in this case, which may be why you are seeing invalid sessions. We have a fix for this that will be released in an upcoming version.

If you're still having issues, is there any log output from the session replay instance?

**Comment by TomFluentjoy** [comment]
thanks for the fast response @crleona.

**Comment by crleona** [comment]
Hi @TomFluentjoy - we've released v0.0.7, which hopefully resolves some of these issues. Please let us know if this persists after you update!

**Comment by TomFluentjoy** [comment]
Hi @crleona cr
regarding to the documentation for setting up the amplitude middle ware by using cocoapods and we are using this setup:

**Comment by TomFluentjoy** [comment]
Hi @crleona 
I have updated the Amplitude to `8.22.0` and right now we can see the session replay on our amplitude dashboard. 
But we also wanted to update the session replay SDK from 0.0.2 to 0.0.7. 
Please reach out if you need more information from our side.

Thanks.

**Comment by crleona** [comment]
Hi @TomFluentjoy - it looks like we've missed some of the version updates for cocoapods, and cross-pod dependencies still seem to have issues. We'll take a look at the latter, but for now, running `pod update` on your current configuration should update to v0.0.8.

**Comment by TomFluentjoy** [comment]
Thanks @crleona.
